### PR TITLE
update-oai-feed

### PR DESCRIPTION
**Pull request by aprilrieger**
Ref ticket: https://github.com/scientist-softserv/oral-history/issues/42

Updates the oai feed

### CODE REVIEW

**Comment by kjallen** [comment]
Checks:

- Confirm data is presented when an item is clicked
- Confirm files have correct urls, example:
    - Go to https://oralhistory-stage.library.ucla.edu/catalog/21198-zz0028td20
    - Expand 'Available Downloads' button, confirm each file exists by clicking on links
- Confirm audio file is correct by pressing play, audio should be present 
- Log into [admin interface](https://oralhistory-stage.library.ucla.edu/admin), click 'Run Importer', should complete in 10-15 minutes

**Comment by emcaulay** [comment]
User Acceptance Testing in progress at UCLA
- @emcaulay and Jane Collings testing

Jane has reviewed the site, and was expecting to see a media asset for this new interview: https://oralhistory-stage.library.ucla.edu/catalog/21198-zz002kpzjw

**Comment by emcaulay** [comment]
UCLA believes our OAI-PMH data feed is not providing the necessary data. We created a ticket in our system to investigate (SYS-1416). UCLA developers will address next week.

**Comment by emcaulay** [comment]
UCLA updated our data to correct a bug, and we think that corrects the problem that Jane reported with the Marshall Happer interview.

**Comment by emcaulay** [comment]
Question for @aprilrieger , I am participating in UAT on the UCLA side, and we found an interview that is not displaying on the oralhistory-stage site that we think should be there.

That record is in the OAI data from the new staff system: https://oh-staff.library.ucla.edu/oai/?verb=GetRecord&identifier=21198/zz002jxzpp

It's available on production: [https://oralhistory.library.ucla.edu/catalog/21198-zz002jxzpp?counter=1](https://oralhistory.library.ucla.edu/catalog/21198-zz002jxzpp?counter=1 )
Here's the URL we think should work on stage: [https://oralhistory-stage.library.ucla.edu/catalog/21198-zz002jxzpp](https://oralhistory-stage.library.ucla.edu/catalog/21198-zz002jxzpp)




[2:04](https://uclalibrary.slack.com/archives/C056EEY6R28/p1696453482583859)
So, unless 
[@Kristian Allen - UCLA](https://uclalibrary.slack.com/team/W01B760CCE4)
 sees something else, I think that's a concrete question for SoftServ: Why is this record not showing on the staging site?

**Comment by aprilrieger** [comment]
@emcaulay  I found the issue, there was an error in the import that was causing the import to error on the remaining 463 works, which includes the one you noted in the ticket as not appearing on staging with the new feed. I was able to import locally no issue, pushed and build in CI, but the Jenkins webhook is giving me a 401 unauthorized (see screenshot) 

@jhriv , IV when you are online can you look into a failure in the Jenkins webhook for the deploy on this actions: https://github.com/UCLALibrary/oral-history/actions/runs/6427646760/job/17453625315 && https://github.com/UCLALibrary/oral-history/actions/runs/6427277222/job/17452694593.

**Comment by aprilrieger** [comment]
Got this deployed and re-imported on staging for your UAT review. I was able to import the full 4707 works and am able to see this work: https://oralhistory-stage.library.ucla.edu/catalog/21198-zz002jxzpp that was not initially on staging with the new oai feed. **Note that I am seeing the titles of some of the works shown as the works id, I am not sure if that is the oai feed needing adjustments so let me know if there is more work for us to accomplish here.

**Comment by emcaulay** [comment]
I commented in Slack, but I am officially turning over the UCLA User Acceptance Testing findings to April and Jill (Scientist) for their review. These are all the findings Jane and I had when reviewing the site on stage. April and Jill, please review. After reviewing, can you let us know in Slack or email what the plan is for addressing them, and especially let us know if a meeting is required to talk through anything.

**Comment by aprilrieger** [comment]
> https://docs.google.com/document/d/1o05c3t-7wMxL_p3evQnP5Po9pZU9_OPjRCkbb0tu-Hc/edit?usp=sharing

Thank you @emcaulay for the turn over. I will review tomorrow and reach out if I have any questions and assess the lift and get some some timelines to you. We may while we are in there be able to just fix it pretty quickly! We have a planning meeting for next months sprint on Monday so this is perfect timing, thank you!

**Comment by aprilrieger** [comment]
@emcaulay  I believe the upgraded k8 deployment is now blocking this work. Shifting my priority to getting the upgrades branch merged into main in order to get everything else in. I am still troubleshooting locally on this ticket, but I wasn't able to get this on staging.

**Comment by aprilrieger** [comment]
Findings from Scientist.com investigation of the UAT Testing for the New UCLA-OH Oai Feed

## Finding 1: Series Items in Search Results on Stage (not on Prod)

- I am seeing the records referenced in the UAT Testing and see the corresponding records in the OAI feed after I curled the results to inspect with: `curl "https://oh-staff.library.ucla.edu/oai/?verb=ListRecords" | xmllint --format - > oh_oai.xml`, these records do not have the type="series" which is why they are showing in the search results. And they also seem to be duplicates as well. 

1. `<identifier>21198/zz001nf1zc</identifier>`
```
    <record>
      <header>
        <identifier>21198/zz001nf1zc</identifier>
        <datestamp>2010-02-24</datestamp>
      </header>
      <metadata>
        <mods:mods xmlns:mods="http://www.loc.gov/mods/v3" xmlns:xlink="http://www.w3.org/1999/xlink">
          <mods:titleInfo>
            <mods:title>Making Democracy Matter: Identity and Activism in Los Angeles</mods:title>
          </mods:titleInfo>
          <mods:abstract>These interviews were conducted by UCLA professor Karen Brodkin and are part of a larger study of a cohort of labor and immigrant worker organizers in Los Angeles who began their activism in the latter 1990s.  The interviews deal with the life paths that led interviewees to full-time activism and with their visions of social justice. The book resulting from this project is Making Democracy Matter: Identity and Activism in Los Angeles (2007, Rutgers University Press). Additional interviews in this series can be accessed through UCLA Library's Department of Special Collections.</mods:abstract>
          <mods:identifier>21198/zz001nf1zc</mods:identifier>
          <mods:language>
            <mods:languageTerm>eng</mods:languageTerm>
          </mods:language>
          <mods:subject authority="cohr">
            <mods:topic>Social Movements</mods:topic>
          </mods:subject>
          <mods:subject authority="cohr">
            <mods:topic>Labor Movement</mods:topic>
          </mods:subject>
        </mods:mods>
      </metadata>
    </record>
```

2. `<identifier>21198/zz002kd0h8</identifier>`
```
    <record>
      <header>
        <identifier>21198/zz002kd0h8</identifier>
        <datestamp>2018-02-12</datestamp>
      </header>
      <metadata>
        <mods:mods xmlns:mods="http://www.loc.gov/mods/v3" xmlns:xlink="http://www.w3.org/1999/xlink">
          <mods:titleInfo>
            <mods:title>Interviews conducted by Constance Coiner for book Better Red</mods:title>
          </mods:titleInfo>
          <mods:abstract>These interviews were conducted by Constance Coiner, a faculty member at SUNY Binghampton and a former graduate student at UCLA, as background for her book Better Red: The Writing and Resistance of Tillie Olsen and Meridel Le Sueur. They were donated to UCLA after her death by her husband, Stephen Duarte.</mods:abstract>
          <mods:identifier>21198/zz002kd0h8</mods:identifier>
          <mods:subject authority="cohr">
            <mods:topic>Communist Party</mods:topic>
          </mods:subject>
          <mods:subject authority="cohr">
            <mods:topic>Literature</mods:topic>
          </mods:subject>
          <mods:subject authority="cohr">
            <mods:topic>Labor Movement</mods:topic>
          </mods:subject>
          <mods:subject authority="cohr">
            <mods:topic>Social Movements</mods:topic>
          </mods:subject>
        </mods:mods>
      </metadata>
    </record>
```

3. `<identifier>21198/zz002b0jrb</identifier>`
```
<record>
      <header>
        <identifier>21198/zz002b0jrb</identifier>
        <datestamp>2011-08-04</datestamp>
      </header>
      <metadata>
        <mods:mods xmlns:mods="http://www.loc.gov/mods/v3" xmlns:xlink="http://www.w3.org/1999/xlink">
          <mods:titleInfo>
            <mods:title>Donde Haiga un Trabajador Explotado, Ah&#xED; Estar&#xE9; Yo: Justice for Janitors' Workers, Organizers, and Allies</mods:title>
          </mods:titleInfo>
          <mods:abstract>This series documents the Justice for Janitors movement in Los Angeles from the 1980s through the early 2000s. Justice for Janitors is a labor organization of the Service Employees International Union that has historically sought to improve the  working conditions and bargaining power of workers in the janitorial services industry. The movement has taken various forms in different cities, with Los Angeles serving as the largest center of activity. By including interviews with labor organizers, politicians, and rank-and-file members, the series aims to offer a comprehensive picture of the Justice for Janitors movement in Los Angeles. In addition to documenting Justice for Janitors, the series also explores many of the participants' experiences in Central America before immigrating to the U.S. and interviewees' involvement in other facets of the labor movement in the U.S. and Central America. This project was generously supported by Arcadia  funds.</mods:abstract>
          <mods:identifier>21198/zz002b0jrb</mods:identifier>
          <mods:subject authority="cohr">
            <mods:topic>Social Movements</mods:topic>
          </mods:subject>
          <mods:subject authority="cohr">
            <mods:topic>Labor Movement</mods:topic>
          </mods:subject>
        </mods:mods>
      </metadata>
    </record>
```

- [ ] UCLA-OH Action Item: Remove the additional record of the series that are not nested inside the parent object.

## Finding 2: Some Session Records are Listed in Search Results (on Stage and not on Prod) - This is Probably an Error

- I am seeing the records referenced in the UAT Testing and see the corresponding records in the OAI feed after I curled the results to inspect with: `curl "https://oh-staff.library.ucla.edu/oai/?verb=ListRecords" | xmllint --format - > oh_oai.xml`, this record is an example of a duplicate record with `<mods:title>SESSION 1 (3/15/2011)</mods:title>` that is showing in the search results page.

```
    <record>
      <header>
        <identifier>21198/zz0028td62</identifier>
        <datestamp>2011-06-09</datestamp>
      </header>
      <metadata>
        <mods:mods xmlns:mods="http://www.loc.gov/mods/v3" xmlns:xlink="http://www.w3.org/1999/xlink">
          <mods:titleInfo>
            <mods:title>SESSION 1 (3/15/2011)</mods:title>
          </mods:titleInfo>
          <mods:physicalDescription>
            <mods:extent>258 pages</mods:extent>
          </mods:physicalDescription>
          <mods:identifier>21198/zz0028td62</mods:identifier>
          <mods:language>
            <mods:languageTerm>eng</mods:languageTerm>
          </mods:language>
          <mods:accessCondition>Regents of the University of California, UCLA Library.</mods:accessCondition>
          <mods:subject authority="cohr">
            <mods:topic>Social Movements</mods:topic>
          </mods:subject>
          <mods:location displayLabel="Interview Full Transcript (TEI/P5 XML)">
            <mods:url>https://static.library.ucla.edu/oralhistory/text/submasters/21198-zz0028td62-2-submaster.xml</mods:url>
          </mods:location>
        </mods:mods>
      </metadata>
    </record>
```

AND the second listing (which is not showing up in the search results as desired)
```
    <record>
      <header>
        <identifier>21198/zz0028td0z</identifier>
        <datestamp>2011-06-09</datestamp>
      </header>
      <metadata>
        <mods:mods xmlns:mods="http://www.loc.gov/mods/v3" xmlns:xlink="http://www.w3.org/1999/xlink">
          <mods:titleInfo>
            <mods:title>Interview of Nancy Angelo</mods:title>
          </mods:titleInfo>
          <mods:note type="personpresent" displayLabel="Persons Present">Angelo and Gordienko.</mods:note>
          <mods:note type="processinterview" displayLabel="Processing of Interview">The transcript is a verbatim transcription of the recording. It was transcribed by a professional transcribing agency using a list of proper names and specialized terminology supplied by the interviewer. Angelo was then given an opportunity to review the transcript and make corrections and additions. Those corrections were entered into the text without further editing or review on the part of the Center for Oral History Research staff.</mods:note>
          <mods:note type="interviewerhistory" displayLabel="Interviewer Background and Preparation">The interview was conducted by Andrey Gordienko, doctoral candidate in Cinema and Media Studies, UCLA School of Theater, Film and Television; Graduate Student Researcher at the Center for the Study of Women, UCLA.</mods:note>
          <mods:note type="biographical" displayLabel="Biographical Information">Performance and video artist. Involved in the Women&#x2019;s Building, a center for feminist art in Los Angeles.</mods:note>
          <mods:note type="supportingdocuments" displayLabel="Supporting Documents">Research relating to the interview are located in the office of UCLA Library's Center for Oral History Research.</mods:note>
          <mods:note type="place" displayLabel="Place Conducted">Angelo&#x2019;s house in San Anselmo, California.</mods:note>
          <mods:physicalDescription>
            <mods:extent>5 hrs.</mods:extent>
          </mods:physicalDescription>
          <mods:identifier>21198/zz0028td0z</mods:identifier>
          <mods:language>
            <mods:languageTerm>eng</mods:languageTerm>
          </mods:language>
          <mods:name>
            <mods:namePart>Gordienko, Andrey</mods:namePart>
            <mods:role>
              <mods:roleTerm type="text">interviewer</mods:roleTerm>
            </mods:role>
          </mods:name>
          <mods:name>
            <mods:namePart>Angelo, Nancy</mods:namePart>
            <mods:role>
              <mods:roleTerm type="text">interviewee</mods:roleTerm>
            </mods:role>
          </mods:name>
          <mods:accessCondition>Regents of the University of California, UCLA Library.</mods:accessCondition>
          <mods:subject authority="cohr">
            <mods:topic>Social Movements</mods:topic>
          </mods:subject>
          <mods:subject authority="cohr">
            <mods:topic>Art</mods:topic>
          </mods:subject>
          <mods:subject authority="cohr">
            <mods:topic>Women's Issues</mods:topic>
          </mods:subject>
          <mods:relatedItem xlink:href="https://wowza.library.ucla.edu/dlp/definst/mp3:oralhistory/21198-zz0028td62-1-submaster.mp3/playlist.m3u8" type="constituent">
            <mods:titleInfo>
              <mods:title>SESSION 1 (3/15/2011)</mods:title>
            </mods:titleInfo>
            <mods:identifier>21198/zz0028td62</mods:identifier>
            <mods:part order="1" type="session_audio"/>
            <mods:tableOfContents>Angelo&#x2019;s childhood in Carson City, Nevada&#x2014;Her father&#x2019;s background&#x2014;Her parents&#x2019; views on religion&#x2014;More on family background&#x2014;Moves to Switzerland at the age of 7&#x2014;On being close to her father&#x2014;On doing household chores and learning to work hard&#x2014;Enduring sickness and loss of vision during childhood&#x2014;Has a great deal of independence as a child, explores the city of Brussels and its history&#x2014;Learns about Jewish history in Belgium and the Holocaust experience&#x2014;Comes to identify with European culture&#x2014;Attends high school in the U.S. and engages in community service programs&#x2014;Repressive environment at high school and restricted private life&#x2014;Enters University of California, Santa Cruz and encounters the hippie culture&#x2014;After one year of college, goes to Denmark to study photography&#x2014;Her close friend is murdered by a serial killer&#x2014;Angelo leaves college and travels back to Europe to work at International Union for Conservation of Nature&#x2014;First experiences with filmmaking and feminist activism at UC Santa Cruz&#x2014;Decides to become a filmmaker while studying in Europe&#x2014;Encounters participants in feminist art movement while at San Francisco Art Institute&#x2014;Her relationship with Bernard Meares&#x2014;Decides to move to Los Angeles to attend Feminist Studio Workshop&#x2014;Falling in love with a woman for the first time&#x2014;Defines the nature of feminist art as it was taught at the Woman&#x2019;s Building&#x2014;Building the Woman&#x2019;s Building&#x2014;Structure of consciousness-raising groups&#x2014;On resistance to abstract modernist art and the emergence of performance art&#x2014;Presence of men at the Woman&#x2019;s Building&#x2014;The significance of collaboration in performance art&#x2014;Performance as &#x201C;public art&#x201D; targeting violence issues&#x2014;On the tension between lesbian and heterosexual women&#x2014;On the marginal presence of ethnic women in the Women&#x2019;s Movement&#x2014;Class tensions in the Women&#x2019;s Movement.</mods:tableOfContents>
          </mods:relatedItem>
          <mods:relatedItem xlink:href="https://wowza.library.ucla.edu/dlp/definst/mp3:oralhistory/21198-zz0028td7k-1-submaster.mp3/playlist.m3u8" type="constituent">
            <mods:titleInfo>
              <mods:title>SESSION 2A (4/11/2011)</mods:title>
            </mods:titleInfo>
            <mods:identifier>21198/zz0028td7k</mods:identifier>
            <mods:part order="2" type="session_audio"/>
            <mods:tableOfContents>On the Feminist Art Workers (FAW), Angelo&#x2019;s first performance art group&#x2014;FAW&#x2019;s early performance piece, Draw Your Own Conclusions&#x2014;Another FAW piece, Pieta Afloat&#x2014;The significance of Angelo&#x2019;s character, Sister Angelica Furiosa&#x2014;The ritualistic aspect of feminist performance art&#x2014;Learning to work in video&#x2014;On teaching and promoting video art&#x2014;On the relationship between video and performance art&#x2014;Equal Time, Equal Space video piece&#x2014;Nun and Deviant&#x2014;Collaborations with other artists&#x2014;&#x201C;Oral Herstory of Lesbianism&#x201D;&#x2014;On gay rights activism&#x2014;The exhibition &#x201C;Bedtime Stories.&#x201D;</mods:tableOfContents>
          </mods:relatedItem>
          <mods:relatedItem xlink:href="https://wowza.library.ucla.edu/dlp/definst/mp3:oralhistory/21198-zz0028td83-1-submaster.mp3/playlist.m3u8" type="constituent">
            <mods:titleInfo>
              <mods:title>SESSION 2B (4/11/2011)</mods:title>
            </mods:titleInfo>
            <mods:identifier>21198/zz0028td83</mods:identifier>
            <mods:part order="3" type="session_audio"/>
            <mods:tableOfContents>The break up of the Feminist Art Workers and the emergence of Sisters of Survival&#x2014;Sisters of Survival&#x2019;s anti-nuclear activism&#x2014;Angelo leaves the Woman&#x2019;s Building&#x2014;Involvement with SPARC&#x2014;Going back to graduate school&#x2014;Angelo&#x2019;s career in organizational psychology&#x2014;Moving back to San Francisco&#x2014;The relation between organization psychology and artistic production&#x2014;On categorization and periodization of feminist art&#x2014;Advice for young feminists.</mods:tableOfContents>
          </mods:relatedItem>
          <mods:relatedItem type="series">
            <mods:titleInfo>
              <mods:title>Women's Activist Lives</mods:title>
            </mods:titleInfo>
            <mods:identifier>21198/zz0028tcxf</mods:identifier>
            <mods:abstract>Women&#x2019;s Activist Lives in Los Angeles is a series of interviews done by graduate research assistants under the auspices of UCLA&#x2019;s Center for the Study of Women.  The series addresses the diverse ways in which women&#x2019;s social movement activities affected public policy and transformed civic institutions such as education, social services, and the art world in Los Angeles. Several of the oral histories also focus on individuals who were involved with the June L. Mazer Lesbian Archives, which the Center for the Study of Women was involved in bringing to UCLA Library Special Collections at the time the oral histories were being done.</mods:abstract>
          </mods:relatedItem>
          <mods:location displayLabel="Interview History">
            <mods:url>https://static.library.ucla.edu/oralhistory/text/submasters/21198-zz0028td0z-1-submaster.xml</mods:url>
          </mods:location>
          <mods:location displayLabel="Interview Full Transcript (Printable Version)">
            <mods:url>https://static.library.ucla.edu/oralhistory/text/submasters/21198-zz0028td0z-2-submaster.html</mods:url>
          </mods:location>
          <mods:location displayLabel="Interview Full Transcript (TEI/P5 XML)">
            <mods:url>https://static.library.ucla.edu/oralhistory/text/submasters/21198-zz0028td0z-3-submaster.xml</mods:url>
          </mods:location>
          <mods:location displayLabel="Interviewee Biography">
            <mods:url>https://static.library.ucla.edu/oralhistory/text/submasters/21198-zz0028td0z-4-submaster.xml</mods:url>
          </mods:location>
          <mods:location displayLabel="Interview Full Transcript (PDF)">
            <mods:url>https://static.library.ucla.edu/oralhistory/pdf/submasters/21198-zz0028td0z-5-submaster.pdf</mods:url>
          </mods:location>
        </mods:mods>
      </metadata>
    </record>
```

- [ ] UCLA-OH Action Item: Remove the additional record of the sessions that are not nested inside the parent object.

## Finding 3: Waveform design missing on new audio on stage

- I am getting the generation of waveforms locally (Unable to deploy to staging to test yet)

## Finding 4: Distorted portrait photos

- The images that were reported as distorted, appear to be distorted from the source. 

1. https://oralhistory-stage.library.ucla.edu/catalog/21198-zz002kpb7j?counter=10 
- Distorted image from source: https://static.library.ucla.edu/oralhistory/submasters/21198-zz002kpb7j-2-submaster.jpg

2. Record: https://oralhistory-stage.library.ucla.edu/catalog/21198-zz002kp1c8?counter=11
- Distorted image from source: https://static.library.ucla.edu/oralhistory/submasters/21198-zz002kp1c8-2-submaster.jpg

## Finding 5: On stage Series Facet includes “Z: Orphan Interviews Pre 1999” and “Z: Orphan Interviews after 1999”

- 417 records with: `<mods:title>Z: SOME TITLE</mods:title>`

- 415 of those records have `<mods:relatedItem type="series">`
```
<mods:relatedItem type="series">
  <mods:titleInfo>
    <mods:title>Z:
```
- The remaining 2 do not have type="series" attribute, and DO NOT SHOW in series facet, id's listed below:
```
<identifier>21198/zz00093sk9</identifier>
<identifier>21198/zz000904xz</identifier>
```
- [ ] UCLA-OH Action Item: If these are not desired in the facets please remove `type="series"` 

## Finding 6: Missing Series “UCLA Asian American Studies”

- Working locally (Unable to deploy to staging to test yet)

## Finding 7: “Has Media” facet shows incorrect count

- Working locally, with count of 599 with audio aka has media (Unable to deploy to staging to test yet)

## Finding 8: Browse by Interviewee Search Results includes Sessions

- SAME as FINDINGS #2

## Finding 9: Video items not showing player on stage

- After curling in the oai feed and inspecting I see all the videos objects reside outside of their parent object. This should be fixed on the ucla-oh side. To get the oai feed I used Andy's method: 
```
curl "[https://oh-staff.library.ucla.edu/oai/?verb=ListRecords](https://www.google.com/url?q=https://oh-staff.library.ucla.edu/oai/?verb%3DListRecords&sa=D&source=docs&ust=1705796584527527&usg=AOvVaw0ogGw4uAjXUn0Gp66AOIJH)" | xmllint --format - > oh_oai.xml
```

- [ ] UCLA-OH Action Item: Need to include video's nested inside the parent object

------------------------------------------------

## Scientist.com Findings
On investigation of xml generation not working locally I was able to see an issue with the new oai feed:

1. XML Transcripts are not being created due to a missing attribute `timed log`

Our logic in the application looks for the attribute `timed log` to start the generation of xml transcripts, which is missing from the new feed.

New OAI Feed
```
<mods:location displayLabel="Interview Full Transcript (TEI/P5 XML)">
  <mods:url>https://static.library.ucla.edu/oralhistory/text/submasters/21198-zz00096kj7-14-submaster.xml</mods:url>
</mods:location>
```
Application Logic:
```
if child.elements['mods:location/mods:url[@usage="timed log"]'].present?
  time_log_url = child.elements['mods:location/mods:url[@usage="timed log"]'].text
  transcript = self.generate_xml_transcript(time_log_url)
  history.attributes["transcripts_json_t"] << {
    "transcript_t": transcript,
    "order_i": order
  }.to_json
  history.attributes["transcripts_t"] = [] if has_xml_transcripts == false
  has_xml_transcripts = true
  transcript_stripped = ActionController::Base.helpers.strip_tags(transcript)
  history.attributes["transcripts_t"] << transcript_stripped
end
```

- [ ] UCLA-OH Action Item: Add `timed log` (however it was added before, I can't see the old oai feed to guide you) to each xml transcript `<mods:url>https://static.library.ucla.edu/oralhistory/text/submasters/21198-zz00096kj7-14-submaster.xml</mods:url>`

2. Noticing that the typeOfResource is no longer used and the code below is now obsolete, so pulling it out of the application unless there are objections:
```
elsif child.name == "typeOfResource"
  history.attributes["type_of_resource_display"] = child.text
  history.attributes["type_of_resource_t"] ||= []
  history.attributes["type_of_resource_t"] << child.text
  history.attributes["type_of_resource_facet"] ||= []
  history.attributes["type_of_resource_facet"] << child.text
end
```

**Comment by emcaulay** [comment]
@kjallen and I met today to review the status of this pull request, and we both felt like all the data in this pull request conversation has made the work very confusing. For all involved, please accept my apologies for the way that this work has ballooned. 

Based on this discussion with Kristian, I am going to take each of the findings from Google Doc and create tickets for either UCLA or Scientist as needed. 

In reviewing the Google Doc (link [here](https://docs.google.com/document/d/1o05c3t-7wMxL_p3evQnP5Po9pZU9_OPjRCkbb0tu-Hc/edit?usp=sharing) for convenience), I think many of the findings have been corrected.

**Comment by emcaulay** [comment]
My suggestion is that we close this pull request as soon as we have a production release of the Oral History End User Web Application that is using the new data source. 

I reviewed oralhistory-stage.library.ucla.edu on 2024-02-13, and there are no problems that should interfere with deploying to production from a content side.

**Comment by emcaulay** [comment]
@aprilrieger , I believe @kjallen has fixed the "timed log" problem. I think I have confirmed that the solution is working, by looking at the following pages:

Interview of Anthony Ortega: [https://oralhistory-stage.library.ucla.edu/catalog/21198-zz0008zrg2](https://oralhistory-stage.library.ucla.edu/catalog/21198-zz0008zrg2)

I looked to see that there were links to the Full Interview Transcript (Printable Version) and Full Interview Transcript (PDF) under the "Available Downloads" section of the interview detail page (link above). I see both of those links. 

Therefore, I think that that the Scientist Finding from listed on this PR has been responded to. I see there is a check box above, but I can't seem to check it off.

**Pull request merged**
